export const ACTION_TYPES = {



  COUNTER_CHANGE: 'COUNTER_CHANGE',
  NAME_CHANGE: 'NAME_CHANGE',
  VALUE_CHANGE: 'VALUE_CHANGE',
  STRING_CHANGE: 'STRING_CHANGE',

  GOAL_CHANGE: 'GOAL_CHANGE',
  GOAL_ID: 'GOAL_ID',

  CHANGENAME: 'CHANGANAME',

  CHANGES: 'CHANGES',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  CHANGE_VALUE: 'CHANGE_VALUE',

  PIN_CODE_REQUESTED: 'PIN_CODE_REQUESTED',
  PIN_CODE_SUCCEEDED: 'PIN_CODE_SUCCEEDED',
  PIN_CODE_FAILED: 'PIN_CODE_FAILED ',

  NAME: 'NAME',

  GET_API_REQUESTED: 'GET_API_REQUESTED',
  GET_API_SUCCEEDED: 'GET_API_SUCCEEDED',
  GET_API_FAILED: 'GET_API_FAILED',
};